### PR TITLE
PLIN-4577 macos notarization

### PR DESCRIPTION
**Pull request by acofer**
# Jira Issue URL
https://inflight.atlassian.net/browse/PLIN-4577

# High-Level Description
Configured github actions with "quill" to sign and notarize mac binaries.
Check it out: https://github.com/skuid/skuid-cli/releases/download/actions_test-0.0.5/skuid_darwin_amd64

# Changelog:

-

### CODE REVIEW

**Review by njdullea — COMMENTED** [review]
Moves the CLI build process from Drone to GitHub actions which supports signing the CLI. Also adds the Mac ARM architecture build.

Is there any way to test it, or just by releasing and making sure the GitHub actions do what is expected?

**Comment by acofer** [comment]
> Is there any way to test it, or just by releasing and making sure the GitHub actions do what is expected?

I already tried it out with some test releases. Download https://github.com/skuid/skuid-cli/releases/download/actions_test-0.0.5/skuid_darwin_arm64, `chmod +x` and see if macOS lets you run it without security settings workarounds. :-)

**Comment by acofer** [comment]
(I don't know if you need admin on the repo, but you can also see some build runs at https://github.com/skuid/skuid-cli/actions)

**Review by njdullea — APPROVED** [review]
Successful GitHub actions output Mac ARM binary!

**Pull request merged**
